export const CLICK_UPDATE_VALUE = 'CLICK_UPDATE_VALUE';
export const RENDER_CARRINHO = 'RENDER_CARRINHO';
export const INCREMENTAR = 'INCREMENTAR';
export const DECREMENTAR = 'DECREMENTAR';
export const ADICIONAR_TOTAL = 'ADICIONAR_TOTAL';
export const REMOVER_TOTAL = 'REMOVER_TOTAL';
